---
# defaults file for ./roles/kubernetes

# This network is required by Flannel.
k8s_pod_network: 10.244.0.0/16

k8s_api_port: 6443

k8s_token:
  token: abcdef.0123456789abcdef
  ttl: "0" # Can also be 1s, 2m, 3h.