---
# defaults file for ./roles/kubernetes

# This network is required by Calico network.
k8s_pod_network: 192.168.0.0/16

k8s_api_port: 6443

k8s_token:
  token: abcdef.0123456789abcdef
  ttl: "0" # Can also be 1s, 2m, 3h.

# Master hostname (used by the workers to join the cluster).
k8s_master_address: k8s1.k8s.local

k8s_load_balancer_range: 10.0.0.200-10.0.0.210

k8s_ingress_ip: 10.0.0.200

k8s_ingress_ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP