---

# Tasks that are common to masters and workers.

- name: ensure firewalld is disabled
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: ensure selinux is disabled
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: ensure swap is disabled in fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: disable swap without restarting the host
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: enable the bridge netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: ensure bridge netfilter module is loaded automatically at boot
  copy:
    content: 'br_netfilter'
    dest: /etc/modules-load.d/br_netfilter.conf
    owner: root
    group: root
    mode: 0640

- name: ensure bridge netfilter is configured for kubernetes
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: import google gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/doc/yum-key.gpg

- name: add kubernetes official yum repository
  yum_repository:
    name: kubernetes
    description: Kubernetes official repository by Google.
    file: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    gpgcheck: no

- name: ensure docker and kubernet packages are installed
  yum:
    name:
      - docker
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: ensure kubelet and docker services are running and enabled
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - kubelet
    - docker

- name: ensure python3 is installed
  yum:
    name: python3
    state: installed

- name: install python libraries required by Ansible k8s module
  pip:
    name:
      - openshift
      - PyYAML
      - kubernetes
    state: present
    executable: pip3